### ISSUE TITLE
Add a Deploy to Heroku button

### ISSUE THREAD

**Issue by GabLeRoux** [jipiboily/forwardlytics#22] opened 2016-04-05 12:10 UTC
Never done this before, but I think it does break some walls and make it easy for new developers to see what the project is and what's the current state of the app.

https://github.com/heroku/button-sample

**Comment by jipiboily** [comment] 2016-04-05 12:58
Duplicate of #19. it's really easy, we just need to add a `app.json` and the button itself in the README. I just need to spend a few minutes on it, probably this week, if no one else did it until then.

**Closed by jipiboily** 2016-04-05 12:58 UTC
